baseURL = 'https://deddison.github.io/'
languageCode = 'en-us'
title = 'Blarg'
theme = 'diary'
module.mounts
  source = '/Users/davideddison/Home/Journal/Posts'
  target = 'content/Users/davideddison/Hugo/blarg/content'