baseURL = 'https://deddison.github.io/public/'
languageCode = 'en-us'
title = 'Blarg'
theme = 'diary'
[module]
[module.mounts]
  source = '/Users/davideddison/Home/Journal/Posts/'
  target = 'content'